package output

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"

	"github.com/miromaik/vow/internal/git"
	"github.com/miromaik/vow/internal/logs"
	"github.com/miromaik/vow/internal/project"
	"github.com/miromaik/vow/internal/system"
)

// ReportData contains all data needed for the report
type ReportData struct {
	Timestamp    string
	System       system.SystemInfo
	Project      project.ProjectType
	EnvVars      []project.EnvVariable
	Dependencies project.Dependencies
	Git          git.GitInfo
	Logs         []logs.LogEntry
}

// GenerateText generates a plain text report from collected data
func GenerateText(data ReportData) string {
	var b strings.Builder

	b.WriteString("================================================================================\n")
	b.WriteString("VOW DEBUG REPORT\n")
	b.WriteString("================================================================================\n")
	b.WriteString(fmt.Sprintf("Generated: %s UTC\n\n", data.Timestamp))

	// System Information
	b.WriteString("SYSTEM INFORMATION\n")
	b.WriteString("--------------------------------------------------------------------------------\n")
	b.WriteString(fmt.Sprintf("Operating System: %s %s\n", data.System.OS, data.System.OSVersion))
	b.WriteString(fmt.Sprintf("Architecture:     %s\n", data.System.Architecture))
	b.WriteString(fmt.Sprintf("Shell:            %s\n", data.System.Shell))
	b.WriteString(fmt.Sprintf("Hostname:         %s\n\n", data.System.Hostname))

	// Project Information
	b.WriteString("PROJECT INFORMATION\n")
	b.WriteString("--------------------------------------------------------------------------------\n")
	b.WriteString(fmt.Sprintf("Type: %s\n", data.Project.Type))
	if data.Project.Version != "" {
		b.WriteString(fmt.Sprintf("Version: %s\n", data.Project.Version))
	}
	if data.Project.PackageManager != "" {
		b.WriteString(fmt.Sprintf("Package Manager: %s", data.Project.PackageManager))
		if data.Project.PMVersion != "" {
			b.WriteString(fmt.Sprintf(" %s", data.Project.PMVersion))
		}
		b.WriteString("\n")
	}

	// Dependencies
	if len(data.Dependencies.Dependencies) > 0 || len(data.Dependencies.DevDependencies) > 0 {
		b.WriteString("\nDependencies:\n")
		if len(data.Dependencies.Dependencies) > 0 {
			keys := sortedKeys(data.Dependencies.Dependencies)
			for _, name := range keys {
				version := data.Dependencies.Dependencies[name]
				b.WriteString(fmt.Sprintf("  - %s: %s\n", name, version))
			}
		}
		if len(data.Dependencies.DevDependencies) > 0 {
			b.WriteString("\nDev Dependencies:\n")
			keys := sortedKeys(data.Dependencies.DevDependencies)
			for _, name := range keys {
				version := data.Dependencies.DevDependencies[name]
				b.WriteString(fmt.Sprintf("  - %s: %s\n", name, version))
			}
		}
	} else {
		b.WriteString("\nNo dependencies found\n")
	}
	b.WriteString("\n")

	// Environment Variables
	b.WriteString("ENVIRONMENT VARIABLES\n")
	b.WriteString("--------------------------------------------------------------------------------\n")
	if len(data.EnvVars) > 0 {
		for _, env := range data.EnvVars {
			b.WriteString(fmt.Sprintf("%s: %s", env.Key, env.Value))
			if env.IsSecret {
				b.WriteString(" (hidden)")
			}
			b.WriteString("\n")
		}
	} else {
		b.WriteString("No .env file found\n")
	}
	b.WriteString("\n")

	// Git Information
	b.WriteString("GIT INFORMATION\n")
	b.WriteString("--------------------------------------------------------------------------------\n")
	if data.Git.IsRepo {
		b.WriteString(fmt.Sprintf("Branch: %s\n", data.Git.Branch))
		if data.Git.LastCommit != "" {
			b.WriteString(fmt.Sprintf("Last Commit: %s", data.Git.LastCommit))
			if data.Git.LastCommitTime != "" {
				b.WriteString(fmt.Sprintf(" (%s)", data.Git.LastCommitTime))
			}
			b.WriteString("\n")
		}
		b.WriteString(fmt.Sprintf("Modified Files: %d\n", data.Git.ModifiedFiles))
		b.WriteString(fmt.Sprintf("Remote: %s\n", data.Git.RemoteURL))
	} else {
		b.WriteString("Not a git repository\n")
	}
	b.WriteString("\n")

	// Recent Errors
	b.WriteString("RECENT ERRORS\n")
	b.WriteString("--------------------------------------------------------------------------------\n")
	if len(data.Logs) > 0 {
		for _, log := range data.Logs {
			b.WriteString(fmt.Sprintf("\n%s:\n", log.Filename))
			b.WriteString(log.Content)
			b.WriteString("\n")
		}
	} else {
		b.WriteString("No error logs found\n")
	}
	b.WriteString("\n")

	b.WriteString("================================================================================\n")
	b.WriteString("Generated by VOW v1.0.0\n")
	b.WriteString("================================================================================\n")

	return b.String()
}

// GenerateMarkdown generates a markdown report from collected data
func GenerateMarkdown(data ReportData) string {
	tmpl := `# VOW Debug Report
*Generated: {{.Timestamp}} UTC*

---

## System Information
- **Operating System:** {{.System.OS}} {{.System.OSVersion}}
- **Architecture:** {{.System.Architecture}}
- **Shell:** {{.System.Shell}}
- **Hostname:** {{.System.Hostname}}

---

## Project Information
**Type:** {{.Project.Type}}
{{- if .Project.Version}}
- **Version:** {{.Project.Version}}
{{- end}}
{{- if .Project.PackageManager}}
- **Package Manager:** {{.Project.PackageManager}}{{if .Project.PMVersion}} {{.Project.PMVersion}}{{end}}
{{- end}}

{{- if or .Dependencies.Dependencies .Dependencies.DevDependencies}}

### Dependencies
{{- if .Dependencies.Dependencies}}
{{- range $name, $version := .Dependencies.Dependencies}}
- {{$name}}: {{$version}}
{{- end}}
{{- end}}

{{- if .Dependencies.DevDependencies}}

### Dev Dependencies
{{- range $name, $version := .Dependencies.DevDependencies}}
- {{$name}}: {{$version}}
{{- end}}
{{- end}}
{{- else}}

*No dependencies found*
{{- end}}

---

## Environment Variables
{{- if .EnvVars}}
{{- range .EnvVars}}
- **{{.Key}}:** {{.Value}}{{if .IsSecret}} *(hidden)*{{end}}
{{- end}}
{{- else}}

*No .env file found*
{{- end}}

---

## Git Information
{{- if .Git.IsRepo}}
- **Branch:** {{.Git.Branch}}
{{- if .Git.LastCommit}}
- **Last Commit:** {{.Git.LastCommit}}{{if .Git.LastCommitTime}} ({{.Git.LastCommitTime}}){{end}}
{{- end}}
- **Modified Files:** {{.Git.ModifiedFiles}}
- **Remote:** {{.Git.RemoteURL}}
{{- else}}

*Not a git repository*
{{- end}}

---

## Recent Errors
{{- if .Logs}}
{{- range .Logs}}

### {{.Filename}}
` + "```" + `
{{.Content}}
` + "```" + `
{{- end}}
{{- else}}

*No error logs found*
{{- end}}

---

*Generated by VOW v1.0.0*
`

	t := template.Must(template.New("report").Funcs(template.FuncMap{
		"sortedKeys": sortedKeys,
	}).Parse(tmpl))

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "Error generating report: " + err.Error()
	}

	return buf.String()
}

// sortedKeys returns sorted keys from a map for consistent output
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
